### ISSUE TITLE
ebdtfunctions.py line 87

### ISSUE THREAD

**Issue by Bisho2122** [CutillasLab/ebdt#1]
Hello there, 

In the following line:
compoundsCellLine = {cellLineHeading.value.split(".")[1]: cellLineHeading.value for cellLineHeading in list(wsFValues.rows)[0][3:len(listOfCompounds)+3]}

why do you start parsing from the 3rd kinase inhibitor, shouldn't it be (list(wsFValues.rows)[0][1:len(listOfCompounds)+1]}. )

Thank you

**Comment by TinyMarsh** [comment]
Thanks for raising the issue and well spotted! The column index should actually start at 2, since the 2nd column should contain FDR values for each phosphosite. The reason we had it set to 3 was because there was also an additional column (in addition to the extra FDR column) that existed in previous iterations of the script that has now been removed. Please see the cell line data in the `requiredFiles` folder for an up-to-date example of what the input data should look like.

**Comment by Bisho2122** [comment]
Thank you for your prompt response and for adjusting the datasets. 

So in the MCF7 datasets, you mentioned in the article that you focused on the analysis of phosphosites with FDR less than 0.01 "The number of phosphosites that met these stringent criteria were 9,326, 9,416 and 12,591, for HL60, MCF7 and NTERA2 cell lines, respectively". In the MCF7 dataset that you just updated in `requiredFiles`, there are 9,416 phosphosites and some of them have FDR values > 0.01. I know that later in the script, one of the thresholds for PDTs is FDR < 0.2. But, I was confused because of the previous statement in the paper. Can you please elaborate on that?. 

Thanks again for your response. Highly appreciated
